### PR TITLE
Master

### PR DESCRIPTION
**Pull request by oltibus**
[sq_AL] translated tomcat/ folder and a partial translations of other folders

### CODE REVIEW

**Comment by carlosrusso** [comment]
@oltibus Are you done with the modifications? If so, do you think the albanian language pack is ready for the marketplace?

**Comment by oltibus** [comment]
@carlosrusso I think I am done. If any changes to be provided, I'll make a new push with every new change

**Comment by oltibus** [comment]
Hi @carlosrusso ! As we're having difficulties on installing the albanian language on Pentaho 6.1, can you make it available on marketplace, so we can download it from there?

**Comment by carlosrusso** [comment]
You modified the file `data/metadata.json`. 
Can you please revert those changes ?

**Pull request closed without merging**
