### PR TITLE
[ta_TA] translated for tamil language

### PR DESCRIPTION
**Pull request by shivasakthi18**
Please review and merge it with master.

Thanks in advance for your support!

### CODE REVIEW

**Comment by sivasakthic** [comment]
Hi,

How to get in Pentaho organization, I would like to do more source for open source. I got lots of ideas.

Please guide me to be a community contributor by fixing bugs, sorting out issues etc.,.

Thanks,
Sivasakthi.

**Comment by sivasakthic** [comment]
Please some one take validate this and do a pull request.  I have a user waiting for this to implement via marketplace

**Comment by sivasakthic** [comment]
Who is taking care of this repository...!  It's been more than a month now.  Someone, please post this language to Pentaho.

**Comment by carlosrusso** [comment]
Hello Sivasakthi,

I noticed you removed the <TRANSLATE ME> tags in some files, but kept the original english string there. Was this intentional?
The installer automatically removes the <TRANSLATE ME> tags, so there's no need for that step.  The tag is meant to help the translators in locating the bits that haven't been translated yet.

**Comment by shivasakthi18** [comment]
Hi,  

Tamil is most ancient language,  in our state we used to make mix of words in common,   if we use pure Tamil Words then people will not understand. 

Thanks, 
Sivasakthi.

**Comment by shivasakthi18** [comment]
Hi Carlos, 

Let me get feed back on this conversion and proceed further based on input I get. 

Thanks, 
Sivasakthi.

**Comment by shivasakthi18** [comment]
Thanks for information on tags,  further I Will make it with tags.

**Comment by carlosrusso** [comment]
It's probably a simple matter of reverting some changes on the files that were not translated to Tamil.

**Comment by shivasakthi18** [comment]
Do you want me to do it?

 I just did all this with the text editor.  Notepad++

**Comment by carlosrusso** [comment]
I reverted the changes on the files that eliminated the `<TRANSLATE ME>` tags and merged this PR manually. Closing the PR

**Comment by sivasakthic** [comment]
Thank you very much.

**Comment by carlosrusso** [comment]
Please try the build at https://github.com/webdetails/pentahoLanguagePacks/releases/tag/8.0-17.11.17-RC3
If it works, we can publish it in the marketplace. The build seems to work on 7.1 and 8.0, there's a good chance it will work in 7.0 as well.

**Comment by shivasakthi18** [comment]
Yes, it works. Please proceed marketplace push.

**Comment by shivasakthi18** [comment]
Please let me know whether it is merged to main..?

**Comment by carlosrusso** [comment]
This is already merged, and is available in the marketplace for versions 7.0 and above.

**Comment by sivasakthic** [comment]
Perfect,  thanks. I updated git Readme file as well.

**Pull request closed without merging**
