### PR TITLE
Changes to Swedish translation

### PR DESCRIPTION
**Pull request by kennethwrife**

### CODE REVIEW

**Comment by carlosrusso** [comment]
Thank you for the pull request. There are conflicts, so I'll need to do a manual merge, which might take some time.  Are you able to solve the conflicts yourself?

**Comment by kennethwrife** [comment]
I can try myself. 
    
    Den 2015-08-10 kl. 13:12, skrev Carlos
      Russo:
    
    
      Thank you for the pull request. There are conflicts, so I'll
        need to do a manual merge, which might take some time. Are you
        able to solve the conflicts yourself?
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
      
                                                  Kenneth Wrife
      
        
        
                    ken@omicron.se (mail addr.
        in use since 1984) 
        Omicron Ceti AB                    Voice:     +46 8 793 09 27 /
        +46 8 793 09 00
        Victoria Tower 3A, plan 23     Mobile:   +46 70 563 71 04
        SE-164 40 KISTA, SWEDEN     Fax:       +46 8 03 94 13
        http://www.omicron.se

**Comment by kennethwrife** [comment]
I am not sure how to resolve the conflicts. Probably something with differences between 5.3 and 5.4 branch.
Can you please do it.

**Comment by carlosrusso** [comment]
Let me know if I should close this pull request

**Comment by kennethwrife** [comment]
Please close it.

**Pull request closed without merging**
